Group type management
overextended/ox_core pull request #62
Opened 2022-12-13 23:55 UTC by Wisfakim

It's management of type for groups. 
Each group can be 'unique' so each player can have one group of this type

It's my first contribution, tell me what i'm doing wrong
Tests : 
https://streamable.com/ju27zj

groups_types table 
![image](https://user-images.githubusercontent.com/16806184/207470029-909a4fe5-451e-4c87-af1f-984340bec223.png)

groups table using in test
![image](https://user-images.githubusercontent.com/16806184/207470074-1b1a00cc-f715-40c1-bc9d-bf4b84db0b8b.png)

2022-12-14 00:01 UTC, thelindat commented
What’s the actual point? If you don’t want to assign people to multiple “jobs” or “gangs” just don’t do that; more a script level restriction than database. Giving it an arbitrary type is fine but unique 🤷

2022-12-14 00:12 UTC, Wisfakim commented
I think it can be offer way to manage the type of groups and prevent player input, like recruit player is already in a gang.
In my mind a lot of roleplay server needs this option.
By the way it's transparent, you can don't set type and it's working like actual.

2022-12-14 13:22 UTC, thelindat requested changes

2022-12-14 13:22 UTC, thelindat commented on database.sql
> +  `code` varchar(20) NOT NULL,
Having the group type as 'code' in the types table is a bit weird.

2022-12-14 13:22 UTC, thelindat commented on database.sql
> +  `label` varchar(20) DEFAULT NULL,
Not sure how useful a type label is necessarily.

2022-12-14 13:22 UTC, thelindat commented on database.sql
> +  `unique` int(1) DEFAULT NULL,
I'd like to use BIT for storing booleans, as it's a bit more clear at a glance.

2022-12-14 13:22 UTC, thelindat commented on server/groups/class.lua
> +---@field type_label = string,
type_label either not useful (above) or should be typeLabel (camel casing).
unique_type should be uniqueType, isUnique, or such.

2022-12-14 13:22 UTC, thelindat commented on server/groups/class.lua
> +            for _ in pairs(player.private.groups) do
Weird to use `_` when using the variable. Would also be good to have an exported function or method to check if a group can be added.

2022-12-14 13:22 UTC, thelindat commented on server/groups/class.lua
> +                    error(("Attempted to add multiple unique group '%s' with '%s' for player.%s"):format(self.type, self.name, player.source))
Throwing an error can be a bit awkward when an error didn't actually occur, especially when pcall isn't a common practice in FiveM.

A standardised warning system has finally been added to FiveM so you can use `warn(message)` instead without ending the current thread, then we need to return a boolean for success/failure.

2022-12-14 18:09 UTC, Wisfakim commented
Changes done, I deleted sql request with LEFT OUTER JOIN, something goes wrong with oxmysql when we got null and join.

2022-12-16 12:11 UTC, Wisfakim commented
This edit break nothing of actual groups purpose.
Maybe you are true, is not my mind. Like already said I think lot of roleplaye server need this, and if you got multiple script to setjob, you can make restriction for it at the core level and for me it's pretty good things. 🤷

For a SQL I don't think is syntax error, the join work great on SQL manager, and work great on oxmysql if no one of type are null.

2022-12-26 12:03 UTC, thelindat commented
> Why shouldn't a player be able to have multiple of the same "type" of group if you as an admin/owner want them to and if you don't want them to just don't assign them to multiple.

That was my initial thought and is why I haven't merged this yet, however there may be cases where you don't want a player to be in several gangs; perhaps having group types and something like `player.hasGroupType('gang')`?

2022-12-26 16:41 UTC, Wisfakim commented
You true Lindat ! It's good solution to implement this feature for external script . I do commit in few days to remove unique column, checkin and write export.

2023-01-02 04:04 UTC, closed without merging